import type { Lang } from "./i18n";

// Extra strings for the public sign-in page (kept separate from the main dictionary).
const ML: Record<string, string> = {
  "Signing in…": "സൈൻ ഇൻ ചെയ്യുന്നു…", "Sign in with the account your school gave you.": "നിങ്ങളുടെ സ്കൂൾ നൽകിയ അക്കൗണ്ട് ഉപയോഗിച്ച് സൈൻ ഇൻ ചെയ്യുക.", "Forgot your password? Ask your principal or class teacher for a reset link.": "പാസ്‌വേഡ് മറന്നോ? റീസെറ്റ് ലിങ്കിനായി പ്രിൻസിപ്പലിനോടോ ക്ലാസ് ടീച്ചറോടോ ചോദിക്കുക.", "Create your school": "നിങ്ങളുടെ സ്കൂൾ ഉണ്ടാക്കുക", "Back to home": "ഹോമിലേക്ക് മടങ്ങുക", "Terms": "നിബന്ധനകൾ", "Privacy Policy": "സ്വകാര്യതാ നയം", "Privacy": "സ്വകാര്യത", "and": "ഒപ്പം", "By signing in you agree to our": "സൈൻ ഇൻ ചെയ്യുന്നതിലൂടെ നിങ്ങൾ ഇവ അംഗീകരിക്കുന്നു:", "Password updated. Please sign in.": "പാസ്‌വേഡ് മാറ്റി. ദയവായി സൈൻ ഇൻ ചെയ്യുക.", "One platform for every school, teacher and parent.": "ഓരോ സ്കൂളിനും അധ്യാപകനും രക്ഷിതാവിനും ഒരൊറ്റ പ്ലാറ്റ്ഫോം.", "Attendance, homework, timetables, exams, leave and messaging — with every school’s data kept separate and secure.": "ഹാജർ, ഹോംവർക്ക്, ടൈംടേബിൾ, പരീക്ഷകൾ, അവധി, സന്ദേശങ്ങൾ — ഓരോ സ്കൂളിന്റെയും ഡാറ്റ വേറിട്ടും സുരക്ഷിതമായും.",
};
const HI: Record<string, string> = {
  "Signing in…": "साइन इन हो रहा है…", "Sign in with the account your school gave you.": "अपने विद्यालय द्वारा दिए गए खाते से साइन इन करें।", "Forgot your password? Ask your principal or class teacher for a reset link.": "पासवर्ड भूल गए? रीसेट लिंक के लिए प्रिंसिपल या कक्षा शिक्षक से पूछें।", "Create your school": "अपना विद्यालय बनाएँ", "Back to home": "होम पर वापस जाएँ", "Terms": "शर्तें", "Privacy Policy": "गोपनीयता नीति", "Privacy": "गोपनीयता", "and": "और", "By signing in you agree to our": "साइन इन करके आप इनसे सहमत हैं:", "Password updated. Please sign in.": "पासवर्ड बदल गया। कृपया साइन इन करें।", "One platform for every school, teacher and parent.": "हर विद्यालय, शिक्षक और अभिभावक के लिए एक मंच।", "Attendance, homework, timetables, exams, leave and messaging — with every school’s data kept separate and secure.": "उपस्थिति, गृहकार्य, समय-सारणी, परीक्षा, अवकाश और संदेश — हर विद्यालय का डेटा अलग और सुरक्षित।",
};

export const trx = (lang: Lang, s: string) => (lang === "ml" ? ML[s] : lang === "hi" ? HI[s] : undefined) ?? s;
