// ---------- pages ----------
const DI=()=>new Date(TODAY+'T00:00:00').getDay()-1;
function schoolPct(d){const a=D.att[d]||{};const v=Object.values(a);return v.length?Math.round(v.filter(x=>x!=='A').length/v.length*100):0}
function annFor(){return D.ann.filter(a=>S.role==='principal'||a.aud==='All'||(S.role==='parent'&&(a.aud==='Parents'||a.aud===stu(S.child).cls))||(S.role==='teacher'&&(a.aud==='Teachers'||tch(S.teacherId).classes.includes(a.aud)))).sort((a,b)=>(b.pin-a.pin)||b.date.localeCompare(a.date))}
const annItem=a=>`<div class="item ${a.pin?'pin':''}"><span class="av" aria-hidden="true">${a.pin?'📌':'📣'}</span><div class="grow"><b>${esc(a.title)}</b> ${badge(a.aud==='All'?'Everyone':a.aud.length<=2?'Class '+a.aud:a.aud,'gray')}<p>${esc(a.body)}</p><span class="sub">${esc(a.by)} · ${short(a.date)}</span></div></div>`;
function periodList(c){return D.tt[c][DI()].map((s,i)=>`<div class="item"><span class="badge">${periodsT[i]}</span><div class="grow"><b>${s}</b><div class="sub">${esc(teacherOf(s).name)}</div></div></div>`).join('')}
function dashboard(){
 if(S.role==='parent'){const s=stu(S.child),c=s.cls,first=s.name.split(' ')[0];
  const pend=D.hw.filter(h=>h.cls===c&&!(D.done[s.id]||{})[h.id]);const st=D.att[TODAY][s.id];
  const le=D.exams.filter(e=>e.done).slice(-1)[0];const up=D.exams.find(e=>!e.done);
  return head(`Hello, parent of ${esc(first)} 👋`,`${esc(s.name)} · Class ${c} · Roll ${s.roll}`,st?badge(st==='P'?'Present today':st==='A'?'Absent today':'On leave today',st==='P'?'ok':st==='A'?'bad':'warn'):badge('Today’s attendance not marked yet','gray'))+
  `<div class="grid g4">${stat('Attendance (14 days)',attPct(s.id)+'%','✅')}${stat('Homework pending',pend.length,'📚','w')}${stat(le.name+' score',pctOf(le.id,s.id)+'%','🎯','b')}${stat('Next exam',up?short(up.date):'—','🗓️')}</div>
  <div class="grid g2" style="margin-top:1rem">${card('Today’s timetable',`<div class="list">${periodList(c)}</div>`)}
  <div class="grid">${card('Homework to finish',pend.length?`<div class="list">${pend.slice(0,4).map(h=>`<div class="item"><label style="display:flex;gap:.7rem;align-items:center;flex:1;min-height:44px"><input type="checkbox" style="width:24px;height:24px;min-height:0" data-c="hwdone" data-id="${h.id}" aria-label="Mark ${esc(h.title)} done"><span><b>${esc(h.title)}</b><br><span class="sub">${h.subj} · due ${short(h.due)}</span></span></label></div>`).join('')}</div>`:empty('All homework done. Great job!'))}
  ${card('Latest announcements',`<div class="list">${annFor().slice(0,2).map(annItem).join('')}</div>`)}</div></div>`}
 if(S.role==='teacher'){const t=tch(S.teacherId),c=S.cls,l=clsStudents(c);const marked=l.some(s=>D.att[TODAY][s.id]);const pl=D.leaves.filter(x=>x.status==='pending'&&t.classes.includes(stu(x.sid).cls)).length;
  const low=l.filter(s=>attPct(s.id)<85);
  const mine=t.classes.map(cc=>D.tt[cc][DI()].map((s,i)=>s===t.subj?`<div class="item"><span class="badge">${periodsT[i]}</span><div class="grow"><b>${t.subj}</b> · Class ${cc}</div></div>`:'').join('')).join('');
  return head(`Good day, ${esc(t.name.split(' ')[0])}! 👩‍🏫`,`${esc(t.subj)} teacher · Classes ${t.classes.join(', ')}`,clsSel())+
  `<div class="grid g4">${stat('Students in '+c,l.length,'🧑‍🎓')}${stat('Today’s attendance',marked?'Marked':'Pending','✅',marked?'':'w')}${stat('Leave to review',pl,'🌴','b')}${stat('Homework posted',D.hw.filter(h=>h.cls===c).length,'📚')}</div>
  <div class="grid g2" style="margin-top:1rem">${card('Quick actions',`<div class="chips"><button class="btn" data-a="go" data-p="attendance">Mark attendance</button><button class="btn sec" data-a="go" data-p="homework">Post homework</button><button class="btn sec" data-a="go" data-p="exams">Enter marks</button><button class="btn sec" data-a="go" data-p="announcements">Announce</button></div>`)}
  ${card('My periods today',mine?`<div class="list">${mine}</div>`:empty('No periods today'))}
  ${card('Needs attention (attendance under 85%)',low.length?`<div class="list">${low.map(s=>`<div class="item"><span class="av">${initials(s.name)}</span><div class="grow"><b>${esc(s.name)}</b><div class="sub">Attendance ${attPct(s.id)}%</div></div><button class="btn sm sec" data-a="chatwith" data-id="${s.id}">Message parent</button></div>`).join('')}</div>`:empty('Everyone is doing great!'))}
  ${card('Announcements',`<div class="list">${annFor().slice(0,2).map(annItem).join('')}</div>`)}</div>`}
 const tot=D.students.length,pa=D.approvals.filter(a=>a.status==='pending').length,pl=D.leaves.filter(l=>l.status==='pending').length;
 return head('School overview 🏫',esc(D.school.name)+' · Academic year '+D.school.year)+
 `<div class="grid g4">${stat('Students',tot,'🧑‍🎓')}${stat('Teachers',D.teachers.length,'👩‍🏫','b')}${stat('Attendance, latest day',schoolPct(DAYS[DAYS.length-2])+'%','✅')}${stat('Waiting for approval',pa+pl,'🛡️','w')}</div>
 <div class="grid g2" style="margin-top:1rem">${card('Attendance trend (last 14 days)',`<div class="cols">${DAYS.slice(0,-1).map(d=>`<div title="${fmt(d)}: ${schoolPct(d)}%"><span>${schoolPct(d)}</span><i style="height:${schoolPct(d)}%"></i><span>${new Date(d+'T00:00:00').getDate()}</span></div>`).join('')}</div>`)}
 ${card('Class attendance',bars(CLASSES.map(c=>({l:'Class '+c,v:clsAtt(c)}))))}
 ${card('Needs your approval',pa?`<div class="list">${D.approvals.filter(a=>a.status==='pending').slice(0,4).map(a=>`<div class="item"><div class="grow"><b>Class ${a.cls}</b> · ${fmt(a.date)}<div class="sub">By ${esc(a.by)}</div></div><button class="btn sm ok" data-a="apprv" data-id="${a.id}" data-v="approved">Approve</button></div>`).join('')}</div><p><button class="btn sm out" data-a="go" data-p="approvals" style="margin-top:.6rem">See all</button></p>`:empty('Nothing pending'))}
 ${card('Announcements',`<div class="list">${annFor().slice(0,2).map(annItem).join('')}</div>`)}</div>`;
}
// ----- attendance -----
function segBtns(sid,v,locked){return `<div class="seg" role="group" aria-label="Attendance for ${esc(stu(sid).name)}">${[['P','Present'],['A','Absent'],['L','Leave']].map(([k,l])=>`<button class="${k} ${v===k?'on':''}" aria-pressed="${v===k}" aria-label="${l}" ${locked?'disabled':''} data-a="att" data-sid="${sid}" data-v="${k}">${k}</button>`).join('')}</div>`}
function attendance(){
 if(S.role==='parent'){const s=stu(S.child);const ab=DAYS.filter(d=>D.att[d]?.[s.id]==='A');const p=DAYS.filter(d=>D.att[d]?.[s.id]&&D.att[d][s.id]!=='A').length;
  return head('Attendance',esc(s.name)+' · Class '+s.cls)+`<div class="grid g3">${stat('Attendance',attPct(s.id)+'%','✅')}${stat('Days present',p,'🟢','')}${stat('Days absent',ab.length,'🔴','r')}</div>
  <div class="grid g2" style="margin-top:1rem">${card('Last 14 school days',`<div class="dots">${DAYS.map(d=>{const v=D.att[d]?.[s.id];return `<div style="text-align:center"><div class="d ${v||'n'}" title="${fmt(d)}">${v||'–'}</div><small class="sub">${new Date(d+'T00:00:00').getDate()}</small></div>`}).join('')}</div><p class="sub" style="margin-top:.8rem">P = Present · A = Absent · L = Leave</p>`)}
  ${card('Absences',ab.length?`<div class="list">${ab.reverse().map(d=>`<div class="item"><div class="grow"><b>${fmt(d)}</b></div>${hasLeave(s.id,d)?badge('Leave approved','ok'):badge('No leave','bad')}</div>`).join('')}</div><button class="btn sm sec" style="margin-top:.7rem" data-a="go" data-p="leave">Apply for leave</button>`:empty('No absences. Perfect!'))}</div>`}
 const {cur,html}=tabs('attendance',[['mark','Mark / edit'],['hist','History']]);const l=clsStudents(S.cls);
 if(cur==='hist')return head('Attendance',null,clsSel())+html+card('',`<div class="tw"><table><thead><tr><th>Student</th>${DAYS.map(d=>`<th>${new Date(d+'T00:00:00').getDate()}</th>`).join('')}<th>%</th></tr></thead><tbody>${l.map(s=>`<tr><td>${esc(s.name)}</td>${DAYS.map(d=>{const v=D.att[d]?.[s.id];return `<td><span class="d ${v||'n'}">${v||'–'}</span></td>`}).join('')}<td><b>${attPct(s.id)}%</b></td></tr>`).join('')}</tbody></table></div>`);
 const ap=D.approvals.find(a=>a.date===S.attDate&&a.cls===S.cls);const cnt=k=>l.filter(s=>D.att[S.attDate]?.[s.id]===k).length;
 return head('Mark attendance',null,clsSel())+html+card('',`<div class="pa" style="justify-content:space-between;margin-bottom:.8rem"><label class="sel">Date<select data-c="attdate">${[...DAYS].reverse().map(d=>`<option value="${d}" ${d===S.attDate?'selected':''}>${fmt(d)}${d===TODAY?' (today)':''}</option>`).join('')}</select></label>
 <div>${ap?badge(ap.status==='approved'?'Approved by principal':'Submitted · waiting for approval',ap.status==='approved'?'ok':'warn'):badge('Not submitted','gray')}</div></div>
 <div class="pa" style="margin-bottom:.8rem">${badge('Present '+cnt('P'),'ok')}${badge('Absent '+cnt('A'),'bad')}${badge('Leave '+cnt('L'),'warn')}${badge('Unmarked '+(l.length-cnt('P')-cnt('A')-cnt('L')),'gray')}<span class="sp" style="flex:1"></span><button class="btn sm sec" data-a="allp">Mark all present</button></div>
 <div class="list">${l.map(s=>`<div class="item" style="align-items:center"><span class="av">${s.roll}</span><div class="grow"><b>${esc(s.name)}</b><div class="sub">Attendance ${attPct(s.id)}%</div></div>${segBtns(s.id,D.att[S.attDate]?.[s.id])}</div>`).join('')}</div>
 <p style="margin-top:1rem"><button class="btn" data-a="attsubmit">Submit for approval</button></p>`);
}
// ----- homework -----
function homework(){
 const c=S.role==='parent'?stu(S.child).cls:S.cls;const sid=S.child;const l=D.hw.filter(h=>h.cls===c).sort((a,b)=>b.due.localeCompare(a.due));
 if(S.role==='parent'){const dn=D.done[sid]||{};const f=S.hwF;const show=l.filter(h=>f==='all'||(f==='done')===!!dn[h.id]);
  return head('Homework','Tick when finished – teachers see progress')+`<div class="chips" style="margin-bottom:1rem">${[['all','All'],['pending','Pending'],['done','Done']].map(([k,t])=>`<button class="chip ${f===k?'on':''}" data-a="hwf" data-k="${k}" aria-pressed="${f===k}">${t}</button>`).join('')}</div>
  <div class="list">${show.length?show.map(h=>`<div class="item"><label style="display:flex;gap:.8rem;flex:1;align-items:flex-start;min-height:44px"><input type="checkbox" style="width:26px;height:26px;min-height:0;flex:none" data-c="hwdone" data-id="${h.id}" ${dn[h.id]?'checked':''}><span><b>${esc(h.title)}</b> ${badge(h.subj)} ${h.due<TODAY&&!dn[h.id]?badge('Overdue','bad'):''}<br>${esc(h.desc)}<br><span class="sub">Due ${fmt(h.due)} · ${esc(h.by)}</span></span></label></div>`).join(''):empty('Nothing here')}</div>`}
 const sts=clsStudents(c);
 return head('Homework',null,clsSel())+`<div class="grid g2">${card('Post new homework',`<form class="form" data-f="hw"><div class="row"><label class="f">Subject<select name="subj">${opts(SUBJ,tch(S.teacherId)?.subj)}</select></label>${field('Due date','due','date',addDays(TODAY,2),'required')}</div>${field('Title','title','text','','required placeholder="e.g. Chapter 5 exercises"')}<label class="f">Instructions<textarea name="desc"></textarea></label><button class="btn">Post to Class ${c}</button></form>`)}
 ${card('Posted for Class '+c,l.length?`<div class="list">${l.map(h=>{const n=sts.filter(s=>(D.done[s.id]||{})[h.id]).length;return `<div class="item"><div class="grow"><b>${esc(h.title)}</b> ${badge(h.subj)}<br><span class="sub">Due ${short(h.due)} · ${esc(h.by)}</span><div class="bt" style="margin:.4rem 0"><i style="width:${Math.round(n/sts.length*100)}%"></i></div><span class="sub">${n}/${sts.length} students done</span></div><button class="ib" data-a="delhw" data-id="${h.id}" aria-label="Delete ${esc(h.title)}">🗑️</button></div>`}).join('')}</div>`:empty('No homework yet'))}</div>`;
}
// ----- diary -----
function diary(){
 const c=S.role==='parent'?stu(S.child).cls:S.cls;const l=D.diary.filter(d=>d.cls===c).sort((a,b)=>b.date.localeCompare(a.date));
 return head('Class diary','Daily notes from teachers',S.role==='teacher'?clsSel():'')+(S.role==='teacher'?card('Write a note',`<form class="form" data-f="diary"><div class="row"><label class="f">Subject<select name="subj">${opts(SUBJ,tch(S.teacherId).subj)}</select></label></div><label class="f">Note for parents<textarea name="text" required></textarea></label><button class="btn">Add to diary</button></form>`)+'<br>':'')+
 `<div class="list">${l.length?l.map(d=>`<div class="item"><span class="av" aria-hidden="true">📝</span><div class="grow"><b>${fmt(d.date)}</b> ${badge(d.subj)}<p>${esc(d.text)}</p><span class="sub">${esc(d.by)}</span></div></div>`).join(''):empty('No diary notes yet')}</div>`;
}
// ----- timetable -----
function timetable(){
 const c=S.role==='parent'?stu(S.child).cls:S.cls;const t=S.role==='teacher'?tch(S.teacherId):null;const di=DI();
 return head('Timetable',S.role==='principal'?'Tap any period to change the subject':'Class '+c,S.role==='parent'?'':clsSel())+card('',`<div class="tw"><table class="tt"><thead><tr><th>Day</th>${periodsT.map((p,i)=>`<th>P${i+1}<br><small>${p}</small></th>${i===2?'<th>Break</th>':''}`).join('')}</tr></thead><tbody>${['Mon','Tue','Wed','Thu','Fri'].map((dn,d)=>`<tr><th>${dn}${d===di?' •':''}</th>${D.tt[c][d].map((s,p)=>`<td class="${d===di?'now':''}" ${S.role==='principal'?`data-a="editcell" data-d="${d}" data-p="${p}" tabindex="0" role="button" aria-label="${dn} period ${p+1}: ${s}. Edit"`:''} style="${t&&s===t.subj?'outline:2px solid var(--brand);outline-offset:-2px':''}">${s}</td>${p===2?'<td class="brk">☕</td>':''}`).join('')}</tr>`).join('')}</tbody></table></div><p class="sub" style="margin-top:.6rem">${t?'Outlined cells are your '+t.subj+' periods. ':''}Highlighted row is today.</p>`);
}
// ----- exams -----
function exams(){
 const r=S.role;const L=r==='parent'?[['sched','Schedule'],['marks','Marks'],['report','Report card']]:r==='teacher'?[['sched','Schedule'],['enter','Enter marks'],['results','Results']]:[['sched','Schedule'],['results','Results'],['manage','Manage exams']];
 const {cur,html}=tabs('exams',L);const c=r==='parent'?stu(S.child).cls:S.cls;const sel=r==='parent'?'':clsSel();
 const exSel=`<label class="sel">Exam<select data-c="exam">${D.exams.map(e=>`<option value="${e.id}" ${e.id===S.exam?'selected':''}>${esc(e.name)}</option>`).join('')}</select></label>`;
 let body='';
 if(cur==='sched'){const l=D.sched.filter(x=>x.cls===c).sort((a,b)=>a.date.localeCompare(b.date));const ex=D.exams.find(e=>!e.done);
  body=card((ex?esc(ex.name):'Exam')+' – Class '+c,`<div class="list">${l.map(x=>`<div class="item"><span class="badge">${short(x.date)}</span><div class="grow"><b>${x.subj}</b><div class="sub">${fmt(x.date)} · ${x.time}</div></div>${r!=='parent'?`<button class="ib" data-a="delsched" data-id="${x.id}" aria-label="Remove">🗑️</button>`:''}</div>`).join('')||empty('No exams scheduled')}</div>`)+
  (r!=='parent'?'<br>'+card('Add exam date',`<form class="form" data-f="sched"><div class="row"><label class="f">Subject<select name="subj">${opts(SUBJ)}</select></label>${field('Date','date','date',addDays(TODAY,12),'required')}${field('Time','time','text','10:00 AM')}</div><button class="btn">Add to Class ${c} schedule</button></form>`):'');}
 if(cur==='enter'){const e=D.exams.find(x=>x.id===S.exam);const sj=SUBJ.includes(S.subj)?S.subj:SUBJ[0];
  body=card('Enter marks',`<div class="pa" style="margin-bottom:.8rem">${exSel}<label class="sel">Subject<select data-c="subj">${opts(SUBJ,sj)}</select></label></div><form data-f="marks"><div class="tw"><table><thead><tr><th>Student</th><th>Marks (out of ${e.max})</th></tr></thead><tbody>${clsStudents(c).map(s=>`<tr><td>${esc(s.name)}</td><td><input type="number" min="0" max="${e.max}" name="${s.id}" value="${D.marks[e.id]?.[s.id]?.[sj]??''}" style="max-width:120px" aria-label="Marks for ${esc(s.name)}"></td></tr>`).join('')}</tbody></table></div><p><button class="btn" style="margin-top:.8rem">Save marks</button></p></form>`);}
 if(cur==='results'){const e=D.exams.find(x=>x.id===S.exam);const l=clsStudents(c).map(s=>({s,p:pctOf(e.id,s.id),rk:rank(e.id,s.id)})).sort((a,b)=>a.rk-b.rk);
  body=card(esc(e.name)+' – Class '+c,`<div class="pa" style="margin-bottom:.8rem">${exSel}${badge('Class average '+avgMark(c,e.id)+'%','ok')}</div><div class="tw"><table><thead><tr><th>Rank</th><th>Student</th><th>Total</th><th>%</th><th>Grade</th></tr></thead><tbody>${l.map(x=>`<tr><td>${x.rk}</td><td>${esc(x.s.name)}</td><td>${total(e.id,x.s.id)}/${e.max*SUBJ.length}</td><td>${x.p}%</td><td>${badge(grade(x.p),gtone(x.p))}</td></tr>`).join('')}</tbody></table></div>`);}
 if(cur==='marks'){const s=stu(S.child);const dn=D.exams.filter(e=>e.done);
  body=card('Subject-wise marks',`<div class="tw"><table><thead><tr><th>Subject</th>${dn.map(e=>`<th>${esc(e.name)} (/${e.max})</th>`).join('')}</tr></thead><tbody>${SUBJ.map(j=>`<tr><td>${j}</td>${dn.map(e=>`<td>${D.marks[e.id][s.id][j]}</td>`).join('')}</tr>`).join('')}<tr><th>Overall %</th>${dn.map(e=>`<th>${pctOf(e.id,s.id)}%</th>`).join('')}</tr></tbody></table></div>`)+'<br>'+card('Latest performance',bars(SUBJ.map(j=>{const e=dn[dn.length-1];return{l:j.split(' ')[0],v:Math.round(D.marks[e.id][s.id][j]/e.max*100)}})));}
 if(cur==='report'){const s=stu(S.child),e=D.exams.find(x=>x.id===S.exam&&x.done)||D.exams[1];const p=pctOf(e.id,s.id);
  body=`<div class="pa" style="margin-bottom:.8rem">${exSel}<button class="btn sec" data-a="print">🖨️ Print / save as PDF</button></div><div class="report card"><div style="text-align:center"><h2 style="margin:0">${esc(D.school.name)}</h2><p class="sub">Progress Report · ${esc(e.name)} · ${D.school.year}</p></div><hr><p><b>${esc(s.name)}</b> · Class ${s.cls} · Roll ${s.roll}</p><table><thead><tr><th>Subject</th><th>Marks</th><th>Out of</th><th>Grade</th></tr></thead><tbody>${SUBJ.map(j=>{const m=D.marks[e.id][s.id][j];return `<tr><td>${j}</td><td>${m}</td><td>${e.max}</td><td>${grade(Math.round(m/e.max*100))}</td></tr>`}).join('')}</tbody></table><p style="margin-top:1rem"><b>Total ${total(e.id,s.id)}/${e.max*SUBJ.length} · ${p}% · Grade ${grade(p)} · Rank ${rank(e.id,s.id)} of ${clsStudents(s.cls).length}</b></p><p class="sub">Attendance: ${attPct(s.id)}% · Remark: ${p>=80?'Excellent work, keep shining!':p>=60?'Good effort. A little more practice will help.':'Needs extra support. Please meet the class teacher.'}</p></div>`;}
 if(cur==='manage'){body=card('Exams',`<div class="list">${D.exams.map(e=>`<div class="item"><div class="grow"><b>${esc(e.name)}</b><div class="sub">Max ${e.max} per subject · ${fmt(e.date)}</div></div>${badge(e.done?'Completed':'Upcoming',e.done?'ok':'warn')}</div>`).join('')}</div>`)+'<br>'+card('Create exam',`<form class="form" data-f="exam"><div class="row">${field('Name','name','text','','required')}${field('Max marks per subject','max','number','50','required min="1"')}${field('Date','date','date',addDays(TODAY,30),'required')}</div><button class="btn">Create exam</button></form>`);}
 return head('Exams & marks',null,(cur==='manage')?'':sel)+html+body;
}
// ----- students -----
function students(){
 const c=S.cls,l=clsStudents(c),le=D.exams.filter(e=>e.done).slice(-1)[0];
 return head('Students','Class '+c+' · '+l.length+' students',clsSel())+`<div class="grid g3">${l.map(s=>`<div class="card"><div style="display:flex;gap:.8rem;align-items:center"><span class="av">${initials(s.name)}</span><div><b>${esc(s.name)}</b><div class="sub">Roll ${s.roll}</div></div></div><div style="margin:.8rem 0" class="pa">${badge('Attendance '+attPct(s.id)+'%',attPct(s.id)>=85?'ok':'bad')}${badge(le.name+' '+pctOf(le.id,s.id)+'%',gtone(pctOf(le.id,s.id)))}</div><button class="btn sm sec" data-a="progress" data-id="${s.id}">View progress</button></div>`).join('')}</div>`;
}
function progressModal(id){const s=stu(id);const ds=D.exams.filter(e=>e.done);const e=ds[ds.length-1];
 openModal(esc(s.name),`<p class="sub">Class ${s.cls} · Roll ${s.roll} · Parent phone ${s.phone}</p><h3>Attendance</h3><div class="dots">${DAYS.map(d=>{const v=D.att[d]?.[s.id];return `<span class="d ${v||'n'}" title="${fmt(d)}">${v||'–'}</span>`}).join('')}</div><h3 style="margin-top:1rem">${esc(e.name)} by subject</h3>${bars(SUBJ.map(j=>({l:j.split(' ')[0],v:Math.round(D.marks[e.id][s.id][j]/e.max*100)})))}<p><b>Overall ${pctOf(e.id,s.id)}% · Rank ${rank(e.id,s.id)}</b></p><button class="btn" data-a="chatwith" data-id="${s.id}">Message parent</button>`)}
// ----- leave -----
function leave(nohead){
 const lv=(l)=>{const s=stu(l.sid);return `<div class="item"><div class="grow"><b>${esc(s.name)}</b> ${badge(l.status,l.status==='approved'?'ok':l.status==='rejected'?'bad':'warn')}<br>${short(l.from)}${l.to!==l.from?' – '+short(l.to):''} · ${esc(l.reason)}${l.note?`<div class="sub">Note: ${esc(l.note)}</div>`:''}</div>${(S.role!=='parent'&&l.status==='pending')?`<div class="pa"><button class="btn sm ok" data-a="lv" data-id="${l.id}" data-v="approved">Approve</button><button class="btn sm bad" data-a="lv" data-id="${l.id}" data-v="rejected">Reject</button></div>`:''}</div>`};
 if(S.role==='parent'){const s=stu(S.child);return head('Apply for leave',esc(s.name))+`<div class="grid g2">${card('New request',`<form class="form" data-f="leave"><div class="row">${field('From','from','date',addDays(TODAY,1),'required')}${field('To','to','date',addDays(TODAY,1),'required')}</div><label class="f">Reason<textarea name="reason" required placeholder="Please tell the teacher why"></textarea></label><button class="btn">Send to class teacher</button></form>`)}${card('My requests',`<div class="list">${D.leaves.filter(l=>l.sid===s.id).map(lv).reverse().join('')||empty('No requests yet')}</div>`)}</div>`}
 const mine=D.leaves.filter(l=>S.role==='principal'||tch(S.teacherId).classes.includes(stu(l.sid).cls));const p=mine.filter(l=>l.status==='pending');
 return (nohead?'':head('Leave requests',p.length+' waiting for review'))+card('Waiting',`<div class="list">${p.map(lv).join('')||empty('All caught up!')}</div>`)+'<br>'+card('History',`<div class="list">${mine.filter(l=>l.status!=='pending').map(lv).join('')||empty('Nothing yet')}</div>`);
}
// ----- messages -----
function messages(){
 let th;if(S.role==='parent'){const s=stu(S.child);th=D.teachers.filter(t=>t.classes.includes(s.cls)).map(t=>({k:s.id+':'+t.id,n:(t.name),sub:t.subj+(D.classTeacher[s.cls]===t.id?' · Class teacher':'')}))}
 else th=clsStudents(S.cls).map(s=>({k:s.id+':'+S.teacherId,n:'Parent of '+s.name,sub:s.name+' · Class '+s.cls}));
 if(!th.find(x=>x.k===S.chat))S.chat=th[0]?.k;const cur=th.find(x=>x.k===S.chat);const msgs=D.chats[S.chat]||[];const me=S.role==='parent'?'p':'t';
 return head('Messages','Private chat between teachers and parents',S.role==='teacher'?clsSel():'')+`<div class="chat"><div class="card" style="padding:.5rem;max-height:480px;overflow:auto">${th.map(x=>{const m=D.chats[x.k]||[];return `<button class="th ${x.k===S.chat?'on':''}" data-a="thread" data-k="${x.k}"><span class="av">${initials(x.n.replace('Parent of ',''))}</span><span><b>${esc(x.n)}</b><br><small class="sub">${esc(m.length?m[m.length-1].text.slice(0,28)+'…':x.sub)}</small></span></button>`}).join('')}</div>
 <div class="card">${cur?`<div style="border-bottom:1px solid var(--line);padding-bottom:.6rem"><b>${esc(cur.n)}</b><div class="sub">${esc(cur.sub)}</div></div><div class="msgs" id="msgs" tabindex="0" aria-label="Conversation">${msgs.length?msgs.map(m=>`<div class="m ${m.f===me?'me':''}">${esc(m.text)}<small>${esc(m.t)}</small></div>`).join(''):empty('Say hello 👋')}</div><form data-f="send" style="display:flex;gap:.5rem"><input name="text" placeholder="Type a message…" aria-label="Message" autocomplete="off" required><button class="btn">Send</button></form>`:empty('No conversations')}</div></div>`;
}
// ----- announcements -----
function announcements(){
 const can=S.role!=='parent';const aud=S.role==='principal'?['All','Parents','Teachers',...CLASSES]:tch(S.teacherId).classes;
 return head('Announcements')+(can?card('New announcement',`<form class="form" data-f="ann">${field('Title','title','text','','required')}<label class="f">Message<textarea name="body" required></textarea></label><div class="row"><label class="f">Send to<select name="aud">${opts(aud.map(a=>[a,a==='All'?'Everyone':CLASSES.includes(a)?'Class '+a:a]))}</select></label>${S.role==='principal'?`<label class="tog" style="border:0">Pin to top<span class="sw"><input type="checkbox" name="pin" aria-label="Pin to top"><span></span></span></label>`:''}</div><button class="btn">Publish</button></form>`)+'<br>':'')+
 `<div class="list">${annFor().map(a=>`<div style="display:flex;gap:.5rem;align-items:flex-start">${annItem(a).replace('class="item','style="flex:1" class="item')}${(S.role==='principal'||a.by.includes(tch(S.teacherId).name))&&S.role!=='parent'?`<button class="ib" data-a="delann" data-id="${a.id}" aria-label="Delete announcement">🗑️</button>`:''}</div>`).join('')||empty('No announcements')}</div>`;
}
// ----- ptm -----
function ptm(){
 return head('Parent–teacher meetings')+(S.role==='principal'?card('Schedule a meeting',`<form class="form" data-f="ptm"><div class="row">${field('Title','title','text','Term 2 Parent–Teacher Meeting','required')}${field('Date','date','date',addDays(TODAY,25),'required')}${field('Venue','venue','text','School Hall')}${field('Start hour (24h)','h','number','10','min="8" max="15"')}</div><button class="btn">Create meeting with 6 slots</button></form>`)+'<br>':'')+
 D.ptm.map(e=>card(esc(e.title),`<p class="sub">${fmt(e.date)} · ${esc(e.venue)}</p><div class="list" style="margin-top:.7rem">${e.slots.map((sl,i)=>{const b=sl.sid?stu(sl.sid):null;const mine=S.role==='parent'&&sl.sid===S.child;
  return `<div class="item" style="align-items:center"><span class="badge">${sl.t}</span><div class="grow">${b?(S.role==='parent'&&!mine?'Booked':'<b>'+esc(b.name)+'</b> · Class '+b.cls):'<span class="sub">Available</span>'}</div>${S.role==='parent'?(mine?`<button class="btn sm bad" data-a="ptmcancel" data-e="${e.id}" data-i="${i}">Cancel</button>`:!sl.sid?`<button class="btn sm" data-a="ptmbook" data-e="${e.id}" data-i="${i}">Book</button>`:badge('Taken','gray')):(b?badge('Confirmed','ok'):'')}</div>`}).join('')}</div>`,'')).join('<br>');
}
// ----- substitutes -----
function substitutes(){
 return head('Substitute log','Who covered which period')+`<div class="grid g2">${card('Log a substitution',`<form class="form" data-f="sub"><div class="row">${field('Date','date','date',TODAY,'required')}<label class="f">Class<select name="cls">${opts(CLASSES)}</select></label>${field('Period','period','number','1','min="1" max="6" required')}</div><div class="row"><label class="f">Absent teacher<select name="absent">${opts(D.teachers.map(t=>t.name))}</select></label><label class="f">Substitute<select name="sub">${opts(D.teachers.map(t=>t.name),D.teachers[1].name)}</select></label></div>${field('Note','note')}<button class="btn">Save</button></form>`)}${card('Recent',`<div class="list">${D.subs.map(s=>`<div class="item"><div class="grow"><b>${esc(s.sub)}</b> covered <b>${esc(s.absent)}</b><br><span class="sub">${fmt(s.date)} · Class ${s.cls} · Period ${s.period}${s.note?' · '+esc(s.note):''}</span></div><button class="ib" data-a="delsub" data-id="${s.id}" aria-label="Delete">🗑️</button></div>`).join('')||empty('Nothing logged')}</div>`)}</div>`;
}
// ----- notifications -----
function notifications(){
 const l=D.notifs.filter(n=>n.to.includes(S.role));
 return head('Notifications',null,`<button class="btn sm sec" data-a="readall">Mark all read</button>`)+`<div class="list">${l.map(n=>`<div class="item" style="${n.read?'opacity:.7':''}"><span class="av" aria-hidden="true">${n.icon}</span><div class="grow">${n.read?'':badge('New')} ${esc(n.text)}<div class="sub">${n.time}</div></div></div>`).join('')||empty('No notifications')}</div>`;
}
// ----- principal pages -----
function analytics(){
 const {cur,html}=tabs('analytics',[['ov','Overview'],['cmp','Class comparison'],['un','Unapproved absences']]);let b='';
 if(cur==='ov')b=`<div class="grid g3">${stat('School attendance (avg)',Math.round(DAYS.slice(0,-1).reduce((a,d)=>a+schoolPct(d),0)/13)+'%','✅')}${stat('Best class',CLASSES.map(c=>[c,clsAtt(c)]).sort((a,b)=>b[1]-a[1])[0][0],'🏆','b')}${stat('Unapproved absences',unapproved().length,'🕵️','r')}</div><br>`+card('Daily attendance',`<div class="cols">${DAYS.slice(0,-1).map(d=>`<div title="${fmt(d)}"><span>${schoolPct(d)}</span><i style="height:${schoolPct(d)}%"></i><span>${new Date(d+'T00:00:00').getDate()}</span></div>`).join('')}</div>`);
 if(cur==='cmp'){const e=D.exams[1];b=`<div class="grid g2">${card('Attendance by class',bars(CLASSES.map(c=>({l:'Class '+c,v:clsAtt(c)}))))}${card(esc(e.name)+' – average marks',bars(CLASSES.map(c=>({l:'Class '+c,v:avgMark(c,e.id)}))))}</div>`}
 if(cur==='un'){const u=unapproved();b=card('Absent without an approved leave',`<div class="pa" style="margin-bottom:.7rem">${badge(u.length+' cases','bad')}<button class="btn sm" data-a="notifyall">Notify all parents</button></div><div class="tw"><table><thead><tr><th>Date</th><th>Student</th><th>Class</th><th>Parent phone</th><th></th></tr></thead><tbody>${u.slice(0,40).map(x=>`<tr><td>${fmt(x.d)}</td><td>${esc(x.s.name)}</td><td>${x.s.cls}</td><td>${x.s.phone}</td><td><button class="btn sm sec" data-a="notify" data-id="${x.s.id}" data-d="${x.d}">Notify</button></td></tr>`).join('')||'<tr><td colspan="5">None 🎉</td></tr>'}</tbody></table></div>`)}
 return head('Analytics')+html+b;
}
function approvals(){
 const {cur,html}=tabs('approvals',[['att','Attendance'],['lv','Leave overview']]);let b='';
 if(cur==='att'){const p=D.approvals.filter(a=>a.status==='pending'),dn=D.approvals.filter(a=>a.status!=='pending').slice(-8).reverse();
  b=card('Waiting for approval',`<div class="list">${p.map(a=>`<div class="item" style="align-items:center"><div class="grow"><b>Class ${a.cls}</b> · ${fmt(a.date)}<div class="sub">Submitted by ${esc(a.by)} · ${clsAtt(a.cls,[a.date])}% present</div></div><div class="pa"><button class="btn sm ok" data-a="apprv" data-id="${a.id}" data-v="approved">Approve</button><button class="btn sm bad" data-a="apprv" data-id="${a.id}" data-v="returned">Return</button></div></div>`).join('')||empty('Nothing waiting')}</div>`)+'<br>'+card('Recently decided',`<div class="list">${dn.map(a=>`<div class="item"><div class="grow">Class ${a.cls} · ${fmt(a.date)}</div>${badge(a.status,a.status==='approved'?'ok':'warn')}</div>`).join('')}</div>`)}
 else b=leave(true);
 return head('Approvals')+html+b;
}
function manage(){
 const {cur,html}=tabs('manage',[['t','Teachers'],['c','Classes'],['s','Students'],['j','Subjects']]);let b='';
 const del=(a,id)=>`<button class="ib" data-a="${a}" data-id="${id}" aria-label="Delete">🗑️</button>`;
 if(cur==='t')b=card('Add teacher',`<form class="form" data-f="addT"><div class="row">${field('Name','name','text','','required')}<label class="f">Subject<select name="subj">${opts(SUBJ)}</select></label>${field('Email','email','email')}${field('Classes (e.g. 6A,6B)','classes','text','6A')}</div><button class="btn">Add teacher</button></form>`)+'<br>'+card('Teachers ('+D.teachers.length+')',`<div class="tw"><table><thead><tr><th>Name</th><th>Subject</th><th>Classes</th><th>Contact</th><th></th></tr></thead><tbody>${D.teachers.map(t=>`<tr><td>${esc(t.name)}</td><td>${t.subj}</td><td>${t.classes.join(', ')}</td><td>${esc(t.email)}</td><td>${del('delT',t.id)}</td></tr>`).join('')}</tbody></table></div>`);
 if(cur==='c')b=card('Add class',`<form class="form" data-f="addC"><div class="row">${field('Class name (e.g. 8A)','name','text','','required')}</div><button class="btn">Add class</button></form>`)+'<br>'+card('Classes',`<div class="list">${CLASSES.map(c=>`<div class="item"><div class="grow"><b>Class ${c}</b><div class="sub">${clsStudents(c).length} students · Class teacher: ${esc(tch(D.classTeacher[c])?.name||'—')}</div></div>${del('delC',c)}</div>`).join('')}</div>`);
 if(cur==='s')b=card('Add student',`<form class="form" data-f="addS"><div class="row">${field('Name','name','text','','required')}<label class="f">Class<select name="cls">${opts(CLASSES)}</select></label></div><button class="btn">Add student</button></form>`)+'<br>'+card('Students ('+D.students.length+')',`<div class="tw"><table><thead><tr><th>Name</th><th>Class</th><th>Roll</th><th>Parent code</th><th></th></tr></thead><tbody>${D.students.map(s=>`<tr><td>${esc(s.name)}</td><td>${s.cls}</td><td>${s.roll}</td><td><code>${s.code}</code></td><td>${del('delS',s.id)}</td></tr>`).join('')}</tbody></table></div>`);
 if(cur==='j')b=card('Add subject',`<form class="form" data-f="addJ">${field('Subject name','name','text','','required')}<button class="btn">Add subject</button></form>`)+'<br>'+card('Subjects',`<div class="list">${SUBJ.map(j=>`<div class="item"><div class="grow"><b>${j}</b><div class="sub">${esc(teacherOf(j).name)}</div></div>${del('delJ',j)}</div>`).join('')}</div>`);
 return head('Manage school')+html+b;
}
function reportRows(t){
 if(t==='att')return [['Class','Students','Avg attendance %'],...CLASSES.map(c=>[c,clsStudents(c).length,clsAtt(c)])];
 if(t==='marks'){const e=D.exams[1];return [['Student','Class','Total','Percent','Grade','Rank'],...D.students.map(s=>[s.name,s.cls,total(e.id,s.id),pctOf(e.id,s.id),grade(pctOf(e.id,s.id)),rank(e.id,s.id)])]}
 if(t==='leave')return [['Student','Class','From','To','Reason','Status'],...D.leaves.map(l=>[stu(l.sid).name,stu(l.sid).cls,l.from,l.to,l.reason,l.status])];
 return [['Name','Class','Roll','Parent code','Parent phone'],...D.students.map(s=>[s.name,s.cls,s.roll,s.code,s.phone])];
}
function reports(){
 const r=reportRows(S.res);return head('Reports','Preview and download as CSV (opens in Excel)')+card('',`<div class="pa" style="margin-bottom:.8rem"><label class="sel">Report<select data-c="res">${opts([['att','Attendance summary'],['marks','Mid Term results'],['leave','Leave register'],['stu','Student list']],S.res)}</select></label><button class="btn" data-a="dl">⬇ Download CSV</button></div><div class="tw"><table><thead><tr>${r[0].map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${r.slice(1,11).map(x=>`<tr>${x.map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></div><p class="sub">Showing first 10 of ${r.length-1} rows</p>`);
}
function settings(){
 const t=S.role==='teacher'?tch(S.teacherId):null;
 const tog=(l,d,on)=>`<div class="tog"><span><b>${l}</b><br><span class="sub">${d}</span></span><span class="sw"><input type="checkbox" ${on?'checked':''} data-c="pref" aria-label="${l}"><span></span></span></div>`;
 return head('Settings')+`<div class="grid g2">${card('Appearance & accessibility',`<div class="tog"><span><b>Text size</b><br><span class="sub">Currently ${Math.round(S.scale*100)}%</span></span><span class="pa"><button class="btn sm sec" data-a="scale" data-d="-1">A−</button><button class="btn sm sec" data-a="scale" data-d="1">A+</button></span></div>${tog('Dark theme','Easier on the eyes at night',S.theme==='dark').replace('data-c="pref"','data-c="darkt"')}${tog('High contrast','Stronger borders and text',S.hc==='on').replace('data-c="pref"','data-c="hct"')}`)}
 ${card('Notifications',tog('Push notifications','Homework, announcements, attendance',true)+tog('Email summaries','Weekly progress email',false))}
 ${t?card('My classes',`<p class="sub">Choose the classes you teach</p><div class="chips" style="margin-top:.6rem">${CLASSES.map(c=>`<button class="chip ${t.classes.includes(c)?'on':''}" aria-pressed="${t.classes.includes(c)}" data-a="tcls" data-c2="${c}">${c}</button>`).join('')}</div>`):''}
 ${S.role==='principal'?card('School profile',`<form class="form" data-f="school">${field('School name','name','text',D.school.name)}${field('Code','code','text',D.school.code)}${field('Academic year','year','text',D.school.year)}${field('Address','address','text',D.school.address)}<button class="btn">Save</button></form>`):''}
 ${S.role==='parent'?card('Child profile',`<p><b>${esc(stu(S.child).name)}</b></p><p class="sub">Class ${stu(S.child).cls} · Code ${stu(S.child).code}</p>`):''}</div>`;
}
const PG={dashboard,attendance,homework,diary,timetable,exams,students,leave,messages,announcements,ptm,substitutes,notifications,analytics,approvals,manage,reports,settings};
function pageHTML(){const f=PG[S.page];return f?f():empty('Page not found')}
